### ISSUE TITLE
Sparsifying sometimes cuts out 2nd to last point, losing useful info

### ISSUE THREAD

**Issue by calcuttj** [LArSoft/larg4#17]
As a result of some behavior in the ParticleListAction (or maybe simply some specifics of how GEANT4 runs), the final trajectory point always has 0 Kinetic Energy. In order to get the particle's true final energy (i.e. before the ending process is invoked), the second to last point can be accessed. However, when sparsifying, the second to last point is sometimes cut out of the trajectory depending on its spacing to other points (the very final point with 0 KE is kept according to the intended behavior of Sparsify). Thus the true end information is lost. 

One fix is to amend Sparsify in MCTrajectory to keep the last 2 points (as opposed to just the last one), but there might be a way to do this in ParticleListAction.

**Comment by knoepfel** [comment]
@calcuttj, please log this issue (and others) at https://cdcvs.fnal.gov/redmine/projects/larsoft/issues/new.

**Comment by calcuttj** [comment]
@knoepfel  Will do. In the future, should I only make issues there? Or should I make both issues and link to here?

**Comment by knoepfel** [comment]
@calcuttj, yes, right now we prefer issues to made in redmine.
